### PR TITLE
December fixes

### PR DESCRIPTION
**Pull request by tie-rack**
Somehow this got in a broken state (tried to run a script that wasn't there). Let's fix that.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Is this still waiting on something?

**Comment by tie-rack** [comment]
This is going to have to wait on an update to quay.io/democracyworks/base (trivial to accomplish, but will require keeping an eye on its other downstream children)

**Comment by cap10morgan** [comment]
What sort of update? Just an apt-get update / upgrade?

**Comment by tie-rack** [comment]
Exactly.

**Comment by tie-rack** [comment]
Build is green, merging.

**Pull request merged**
